---
# Setup Galaxy Trackster
#
#   https://wiki.galaxyproject.org/VisualizationSetup

- name: Assure Trackster len files dir exists
  file: state=directory path="{{ len_file_path }}"  #"
  become_user: "{{ galaxy_user_name }}"

- name: Download .len files
  get_url: url=https://s3.amazonaws.com/cloudman/files/len-files.tar.gz dest=/tmp/len-files.tar.gz timeout=30
  become_user: "{{ galaxy_user_name }}"

- name: Unarchive .len files
  unarchive: copy=no src=/tmp/len-files.tar.gz dest={{ len_file_path }}
  become_user: "{{ galaxy_user_name }}"

- name: Remove downloaded gzipped len file
  file: path=/tmp/len-files.tar.gz state=absent

- name: Assure generic tools bin dir exists
  file: state=directory path={{ galaxy_custom_tools_dir }}

- name: Download Trackster-required utilities
  get_url: url={{ item }} dest={{ galaxy_custom_tools_dir }} mode=0755
  with_items:
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig
    - http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit

- name: Download bedtools source
  get_url: url=https://github.com/arq5x/bedtools2/releases/download/v{{ bedtools_version }}/bedtools-{{ bedtools_version }}.tar.gz dest=/tmp/bedtools2.tar.gz

- name: Extract bedtools source
  unarchive: copy=no src=/tmp/bedtools2.tar.gz dest=/tmp/

- name: Make bedtools
  command: chdir=/tmp/bedtools2 make

- name: Copy bedtools binaries
  shell: cp /tmp/bedtools2/bin/* {{ galaxy_custom_tools_dir }}/.

- name: Remove downloaded bedtools tarball
  file: path=/tmp/bedtools2.tar.gz state=absent

- name: Remove tmp bedtools dir
  file: path=/tmp/bedtools2 state=absent
